version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    restart: on-failure
    volumes:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    network_mode: host
    #ports:
    #  - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana

      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    network_mode: host
    #ports:
    #  - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
