version: '3'


services:
  promtail:
    image: grafana/promtail:latest
    volumes:
#      - /var/log:/var/log 
       - ~/.pm2/logs:/.pm2/logs
       - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    network_mode: host

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
     # - ./loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: host
