auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true
    dir: /tmp/wal

schema_config:
  configs:
    - from: ".*"
      store: "local"
      object_store: "filesystem"
      schema: "v11"
      index:
        prefix: "loki_index_"
        period: "24h"

storage_config:
  local:
    directory: /tmp/chunks

compactor:
  working_directory: /tmp/compactor
  shared_store: filesystem

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

positions:
  filename: /tmp/positions.yaml

client:
  url: http://localhost:3100/loki/api/v1/push
  external_labels:
    job: varlogs

server:
  http_listen_port: 3100

